name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *" # Berjalan setiap 6 jam
  workflow_dispatch: # Memungkinkan menjalankan manual dari tab Actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Memberikan izin menulis ke repositori
    
    steps:
      - uses: actions/checkout@v3

      # Menggenerasi animasi snake
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: alvithops
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Mengirim hasil ke branch 'output'
      - name: Push changes
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
